### ISSUE TITLE
OSX keyboard layout doesn't seem to do cartouches

### ISSUE THREAD

**Issue by MrEgggga** [Id405/sitelen-pona-ucsur-guide#8]
or i just don't know how to do those

**Comment by Id405** [comment]
Which font are you using in combination with this? Fonts such as Fairfax use a slightly different spec for cartouches than fonts like linja nanpa.

**Comment by MrEgggga** [comment]
i'm using linja nanpa; typing [ in the Mac keyboard doesn't let me confirm for some reason, doesn't even do the unknown character thingy

**Comment by MrEgggga** [comment]
also, in discord, typing [_T_ and then E will result in [_T_[_T_E or similar, and pressing other buttons will add more repetitions.

**Comment by Id405** [comment]
ona li pona tan wile ante #9
